Ex1
itayg43/monday-u-exercises pull request #3
Opened 2022-05-20 16:37 UTC by itayg43

2022-05-27 08:06 UTC, SergeiSafrigin commented on src/ex1/js/script.js
> +const clearBtn = document.querySelector(".todo__clear");
having all the elements outside here requires all the dom elements to exist when this file is loaded, which might not be the case in complex web apps that dynamically change the dom depending on the view

2022-05-27 08:36 UTC, SergeiSafrigin commented on src/ex1/index.html
> +    <link rel="stylesheet" href="./css/normalize.css" />
Big like!

2022-05-27 08:45 UTC, SergeiSafrigin commented on src/ex1/index.html
> +          <li id="todo__item-template" class="todo__item hidden">
😍 epic!

2022-05-27 09:39 UTC, SergeiSafrigin commented on src/ex1/index.html
> +        <section class="todo__pending">
should probably be part of the footer

2022-05-27 09:41 UTC, SergeiSafrigin commented on src/ex1/js/script.js
> +let state = readFromLocalStorage(STATE_STORAGE_KEY) || initState();
brilliant! really liked how you handled that state of the app

2022-05-27 09:46 UTC, SergeiSafrigin commented on src/ex1/js/script.js
> +function initListWithDataFromStorage() {
consider changing the name to the more general term initiTodoList to decouple the initial state loading logic from the init todo list logic

2022-05-27 09:48 UTC, SergeiSafrigin commented on src/ex1/js/script.js
> +    pending: 0,
consider implementing a function for calculating the pending number instead of syncing it to avoid out-of-sync bugs all-together

2022-05-27 09:52 UTC, SergeiSafrigin commented on src/ex1/css/style.css
> +  --medium-gray-color: #c3c3c3;
Well done on using CSS variables 🚀

2022-05-27 10:44 UTC, SergeiSafrigin commented on src/ex1/css/style.css
> +  text-overflow: ellipsis;
nice!

2022-05-27 10:47 UTC, SergeiSafrigin commented on src/ex1/css/style.css
> +  background-color: black;
it's a good practice to align the base style of different components such as "button", to avoid code duplication, improve maintainability & have a consistent UI across the app.
You can add a button class with that base style and apply it to all the buttons.

(same goes for input and other components)

2022-05-27 11:05 UTC, SergeiSafrigin commented on src/ex1/js/script.js
> +  todo.isDone = !todo.isDone;
mutating the state directly (and complex data structures in general) is considered a bad practice as other parts of the code might be using it, not expecting it to suddenly change. 
Read more on pure functions and the immutability approach in coding  https://css-tricks.com/understanding-immutability-in-javascript/

2022-05-27 11:11 UTC, SergeiSafrigin commented on src/ex1/js/script.js
> +function handleAlertItem(id) {
you can make this function name more descriptive to improve code readability so you could only read the function name and understand what will happen without reading the implementation, ex: alertItemName(id) / alertItemNameById(id)

2022-05-27 11:12 UTC, SergeiSafrigin commented on src/ex1/js/script.js
> +  const todo = state.todos.find((todo) => todo._id === id);
this code is written 3 times, better move it into a function :)

2022-05-27 11:13 UTC, SergeiSafrigin commented on src/ex1/js/script.js
> +  if (confirm(DELETE_CONFIRMATION_MESSAGE)) {
good use of consts gj!

2022-05-27 11:14 UTC, SergeiSafrigin commented on src/ex1/js/script.js
> +      todos: state.todos.filter((todo) => todo._id !== id),
nice immutable update of the state!

2022-05-27 11:17 UTC, SergeiSafrigin commented on src/ex1/js/script.js
> +  return [...todos];
no need to return a copy as you didn't mutate the list

2022-05-27 11:18 UTC, SergeiSafrigin commented on src/ex1/js/script.js
> +    filteredTodos.sort(sortTodosByValue);
An easier to implement approach might be:
filteredTodos.map(todo => todo.value.toLowerCase()).sort()

2022-05-27 11:23 UTC, SergeiSafrigin commented on src/ex1/js/script.js
> +  todos.forEach((todo) => list.appendChild(todo.elementRef));
nice and clean! I like it

2022-05-27 11:29 UTC, SergeiSafrigin commented on src/ex1/js/script.js
> +  let elIndex = ELEMENTS[CHECKBOX];
Consider querying the item node for the different elements by class name for better maintainability, as you don't want to change this code every time the template structure changes a bit

2022-05-27 11:30 UTC, SergeiSafrigin requested changes
See comments :)

2022-05-29 09:08 UTC, itayg43 commented on src/ex1/index.html
> +        <section class="todo__pending">
fix.

2022-05-29 09:14 UTC, itayg43 commented on src/ex1/js/script.js
> +function initListWithDataFromStorage() {
fix.

2022-05-29 09:17 UTC, itayg43 commented on src/ex1/js/script.js
> +const generateId = (length = ID_LENGTH) => Math.random().toString(length);
fix.

2022-05-29 09:36 UTC, itayg43 commented on src/ex1/js/script.js
> +    pending: 0,
fix.

2022-05-29 09:36 UTC, itayg43 commented on src/ex1/js/script.js
> +  todo.isDone = !todo.isDone;
fix.

2022-05-29 09:40 UTC, itayg43 commented on src/ex1/js/script.js
> +  return [...todos];
fix.

2022-05-29 09:44 UTC, itayg43 commented on src/ex1/js/script.js
> +function handleAlertItem(id) {
fix.

2022-05-29 09:45 UTC, itayg43 commented on src/ex1/js/script.js
> +  if (todoList.childElementCount > 1) {
fix.

2022-05-29 10:04 UTC, itayg43 commented on src/ex1/css/style.css
> +  background-color: black;
fix.

2022-05-30 00:32 UTC, itayg43 commented on src/ex1/js/script.js
> +  let elIndex = ELEMENTS[CHECKBOX];
fix.

2022-05-30 00:53 UTC, itayg43 commented on src/ex1/js/script.js
> +  const todo = state.todos.find((todo) => todo._id === id);
fix.

2022-05-30 01:20 UTC, itayg43 commented on src/ex1/js/script.js
> +    filteredTodos.sort(sortTodosByValue);
I really like the way, but I will lose my elementRef in the map and won't be able to append the items in the append multiple todos to list function on the following line. other suggestion?

2022-05-30 02:22 UTC, itayg43 commented on src/ex1/js/script.js
> +const clearBtn = document.querySelector(".todo__clear");
I think I fixed it...
I create onDOMReady as I saw in the solution with listeners, and also create utils get functions for some elements I need to get access to in several places, like todo input, todo list, and more.
also, after deleting the list item template selector and clearing the list I had a bug when trying to add new todo because the template was deleted from the list and we also don't have a pointer anymore, so now I supply to the replace children function the list item template to clear all and replace it with the hidden template...

2022-06-04 15:39 UTC, merged